export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE'
};

export const tweetConstants = {
    GETALL_REQUEST: 'TWEET_GETALL_REQUEST',
    GETALL_SUCCESS: 'TWEET_GETALL_SUCCESS',
    GETALL_FAILURE: 'TWEET_GETALL_FAILURE',

    ADD_REQUEST: 'TWEET_ADD_REQUEST',
    ADD_SUCCESS: 'TWEET_ADD_SUCCESS',
    ADD_FAILURE: 'TWEET_ADD_FAILURE',

    UPDATE_REQUEST: 'TWEET_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'TWEET_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'TWEET_UPDATE_FAILURE',

    DELETE_REQUEST: 'TWEET_DELETE_REQUEST',
    DELETE_SUCCESS: 'TWEET_DELETE_SUCCESS',
    DELETE_FAILURE: 'TWEET_DELETE_FAILURE',

    SEARCH_QUERY: 'SET_SEARCH_QUERY'
};